# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ca9c546986478d3dc10fb48beb85602d8c69b34de7a6458f6931cf8988adb96d2a4c122a96df985db50348f8d97d0d4e19aec185627fb1800e54bc3d04afadd

test:
  secret_key_base: 4137d7af1e73f3cc4f82e5c29b75403557e227068cec94b64c6ad562e0213f088b71ba0d50cedb1555ade8623ea3f9651df3384074cbc2a670f67e02dd7510c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
